### ISSUE TITLE
`set_override` doesn't react immediately

### ISSUE THREAD

**Issue by neepl** [mackwic/colored#101]
Hi! I'm using `set_override` to disable color output for my tests at their start and use `unset_override` at their end. Time to time tests could fail. The reason is I'm still getting colored output. Could this issue be related to `Ordering::Relaxed` memory ordering used in override methods?

**Comment by spenserblack** [comment]
Since tests are run in parallel, you're likely hitting a race condition. A few ways to work around that could include
- [setting an environment variable to disable coloring instead](https://docs.rs/colored/2.0.0/colored/control/struct.ShouldColorize.html#method.from_env)
- Combining all tests that set/unset the override into one test so that they don't interfere with each other
- Use [a mutex](https://doc.rust-lang.org/std/sync/struct.Mutex.html) to force the tests that set/unset override to wait on each other
- I think `cargo test --jobs 1` would force only 1 test to run at a time

**Comment by neepl** [comment]
Thanks, probably missed that my tests are running in parallel. I've already fixed this with recommendation from colored's crate page: use "colored/no-color" feature for test.
