### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by droundy** [mackwic/colored#20]
You already have this as a TODO, but I'm submitting it as an issue so I can watch for it to be closed.  :)

**Comment by mackwic** [comment]
Hi @droundy thanks for the issue. Since you opened it, I'll add that I don't have the tools, the knowledge, or the motivation/time to work on it. Without any windows machine, it's a hassle.

I think I would implement it by introducing `cprint!()`, `cprintln!()`, `ceprint!()`, and `ceprintln!()` macros, which would act like their stdlib counterpart, but using the [termcolor lib](https://github.com/BurntSushi/ripgrep/tree/master/termcolor) to control the terminal coloring instead of ANSII escapes. Which means runtime parsing or changing the internal structure. Both are possible.

**Comment by droundy** [comment]
I don't have an immediate need for windows support (fac will build and run on windows, but not well, and not yet tested), so I don't see any urgency here.  In fact, since you mentioned the termcolor lib, I just looked into that and switched to termcolor, which suits my needs just fine.

**Comment by m4b** [comment]
@mackwic you could potentially steal the term_painter idea and do: https://github.com/LukasKalbertodt/term-painter/blob/aef0c0042854894facadea18186d5721c9fade07/src/lib.rs#L431

e.g., store a global handle to the output as a static local.

It would take some doing but I think you could keep this totally amazing API (:heart:) _and_ also support windows

**Comment by repi** [comment]
It would be nice if `colored` on Windows right now defaulted to have coloring output disabled by default on Windows until it is supported later (on certain Windows version). That would work better out of the box.

Currently I do this manually on startup, which works but not ideal for everyone to have to do when using the lib on Windows / multi-platform:

```rust
    if cfg!(target_os="windows") {
        // disable colored text output on Windows as the Windows terminals do not support it yet
        colored::control::set_override(false);
    }
```

**Comment by kurtlawrence** [comment]
I have made a PR with a flag to make this work https://github.com/mackwic/colored/pull/47.

**Comment by mackwic** [comment]
PR has been merged ! 🎉 

Thanks a lot for the discussion, and to @kurtlawrence for actually doing the work. :)
