### ISSUE TITLE
Convert between bright and non-bright colours

### ISSUE THREAD

**Issue by arzg** [mackwic/colored#72]
I would like it if there was a way to convert, say `Color::Red` to `Color::BrightRed` and back again with a method, maybe by splitting out the bright colours from `Color` into `BrightColor`. To convert,  methods such as `.bright()` on `Color` and `.normal()` on `BrightColor` could be added.

**Comment by kurtlawrence** [comment]
Hi @arzg,

Could you please provide a use case example?

**Comment by arzg** [comment]
Today I was toying around with creating a [Civilization](https://en.wikipedia.org/wiki/Civilization_(series))-like game with a TUI, and I was considering how I’d implement [Fog of War](https://civilization.fandom.com/wiki/Fog_of_war) for areas of the map that have already been explored. I realised that a nice way to accomplish this would be to represent terrain types as _bright_ text cell background colours, with the explored Fog of War areas having non-bright background colours.

**Comment by kurtlawrence** [comment]
Would it be better to have methods to extract the 3 values of a `ColoredString`?

For example:

```rust
impl ColoredString {
	pub fn fgcolor(&self) -> Option<Color>;
	pub fn bgcolor(&self) -> Option<Color>;
	pub fn style(&self) -> Style;
}
```

The `Style` could also have a method that can check if it contains one of the `Styles`.

This way, rather than implementing very specific functions, you can check if the background colour is a bright variant or not, and appropriately flip.

**Comment by arzg** [comment]
Sounds good to me!
