### ISSUE TITLE
Feature Request: Pass color as argument to make it easier to set it from a variable

### ISSUE THREAD

**Issue by whatisgravity** [mackwic/colored#9]
For example I have a *.conf that saves a color value for the UI, it seems like it would be easier if it was possible to be able to do .color("green") or .color(config.ui_color)

**Comment by mackwic** [comment]
Hmmm. I like the idea, but I wonder if passing a string is the best way to do it. Open strings are by nature ambiguous: should I say `bold green` or `green bold` ? Or `light green` as `tput` says it ?

What about this:
- there is [the `Color` enum](https://github.com/mackwic/colored/blob/master/src/color.rs#L3)
- I can implement `From<&str>` for `Color` and `Colorize::color(&self, Color)`
- So that we can do `"plop".color("green".into())` or `"plop".color(Color::from(config.ui_color))`.

What do you think ?

**Comment by sunjay** [comment]
@mackwic That's great! Even without the FromStr would totally work because like you said the enumeration variants are better than strings anyway.

**Comment by mackwic** [comment]
Wish granted ! 🎉 This is now implemented in PR #18. Closing this issue, feel free to re-open it if it needs more work, or comment if you want to say anything. :)

See the example `dynamic_color.rs` for usage. Pretty straight-forward.
